### PR TITLE
update websocket to not warn on deprecated functions so that build ca…

### PR DESCRIPTION
**Pull request by millibeckers**
…n pass

### CODE REVIEW

**Review by MLawlz — APPROVED** [review]
👍

**Review by jclin — APPROVED** [review]
👍 . As an aside, was the build server treating warnings as errors?

On second thought, 👂 no evil 👀 no evil.

**Comment by millibeckers** [comment]
We have a ticket to go back and fix this for real, this is just to get it compiling so that we could get the build jobs running

**Comment by jclin** [comment]
👍

**Pull request merged**
